name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Output version code
      run: echo VERSION_CODE=${{ github.run_number }} > ./version.properties
    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
      # Some times is have problems with permissions for ./gradle file. Then uncommit it code
      #    - name: Make gradlew executable
      #      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: notification_tracker
        path: app/build/outputs/apk/release/notification_tracker.release.apk
